### ISSUE TITLE
Webjar Source in typesafe repo

### ISSUE THREAD

**Issue by dsanchez31** [ReactiveMongo/ReactiveMongo-Extensions#15]
Hi,

Is it possible to add source into webjar reactivemongo-extensions-json 0.10.5.0.0.akka23 on typesafe repo ?

Thanks !

**Comment by fehmicansaglam** [comment]
Sorry, what do you mean by webjar? 0.10.5.0.0.akka23 is already on maven central. Isn't this sufficient? https://github.com/ReactiveMongo/ReactiveMongo-Extensions/tree/0.10.5.x.akka23#using-reactivemongo-extensions-in-your-project

**Comment by dsanchez31** [comment]
I'm using it into my play 2.3.8 web app and it s working percfectly.

I'm using eclipse to edit my code after running the command 'eclipse with-source=true'. When i try to see the source code of one of my declared webjar module, eclipse can find and display it but not for the reactivemongo json ectensions....

The typesafe repository of your module seems to only containt dist and not the source.

David

**Comment by fehmicansaglam** [comment]
sources.jar seems to be there. http://search.maven.org/#search%7Cga%7C1%7Creactivemongo
You may try downloading and adding it manually.

**Comment by dsanchez31** [comment]
Ok.

I'm using the following resolver  :

resolvers += "Typesafe repository" at "https://repo.typesafe.com/typesafe/releases/"

And the following dependency :

"org.reactivemongo" %% "reactivemongo-extensions-json" % "0.10.5.0.0.akka23"

My play project doesn't get javasource automatically as it can do with my other dependecies (ex: 
"org.reactivemongo" %% "play2-reactivemongo" % "0.10.5.0.akka23"
)

May I really need to add sources manually ? How can I configure my play project to automatically use the given reactivemongo-extensions-json release and get its sources automatically ?

Thanks !

**Comment by dsanchez31** [comment]
Ok I found my problem.

It's due to my local .ivy cache ! I clear it and all is now working !

Sorry for this newbie question...
