### ISSUE TITLE
What's the point to have ExecutionContext implicit parameter on BsonDao class?

### ISSUE THREAD

**Issue by 4lex1v** [ReactiveMongo/ReactiveMongo-Extensions#16]
I'm talking about this:

```scala
abstract class BsonDao[Model, ID](db: => DB, collectionName: String)(implicit modelReader: BSONDocumentReader[Model],
  modelWriter: BSONDocumentWriter[Model],
  idWriter: BSONWriter[ID, _ <: BSONValue],
  lifeCycle: LifeCycle[Model, ID] = new ReflexiveLifeCycle[Model, ID],
  ec: ExecutionContext) // <-- THIS ONE
```

Basically all declared functions are accepting their own ctx, so they will use `ExecutionContext` available on the call-site, not the provided one. Am i missing something or it can be removed? I have a separate configurable dispatcher for mongo related queries and don't really like the idea to capture global context, even if it's not used anywhere.

**Comment by fehmicansaglam** [comment]
If I am not mistaken it is there only for creating the declared autoindexes. But I don't have a solution to remove it. Do you have an idea?

**Comment by 4lex1v** [comment]
The actual problem if one uses different `ExecutionContext` then it's a bit hard in some cases not to capture both context with Dao. I was missing the call to `ensureIndexes`, i think removing this call is not an option, but then it possible to remove additional implicit parameter from all functions in [Dao](https://github.com/ReactiveMongo/ReactiveMongo-Extensions/blob/0.10.x/core/src/main/scala/dao/Dao.scala) (so as in BsonDao and JsonDao), then all these function will use the context provided in the constructor list, which also solves the problem.

**Comment by fehmicansaglam** [comment]
Removing the implicit parameter from methods is not an option because most
users depend on this functionality. I should give some more thought on this.

**Comment by cchantep** [comment]
In case you have several `ExecutionContext`, you can ensure the one you want is used by (re)declaring it the clorer possible to the call.

```scala
implicit val ec: ExecutionContext = yourPreferedContext
new YourBsonDao[Model, ID](db, colName)
```

If you have more questions, you can use the [MailingList](https://groups.google.com/forum/?fromgroups#!topic/reactivemongo/gC5vLErbq8E). Best regards.
