### ISSUE TITLE
Downloading big file with FileDAO generates memory error

### ISSUE THREAD

**Issue by dsanchez31** [ReactiveMongo/ReactiveMongo-Extensions#17]
Hi,

Serving a big file using gridfs generates a memory error.

Adding gfs.ensureIndex() will fix my problem. Maybe it could be done by default in FileDAO object.

Thanks

**Comment by fehmicansaglam** [comment]
Can you please share a code snippet? How are you trying to download the file?

**Comment by dsanchez31** [comment]
Here how I serve a file :

def get(id: BSONObjectID) = UserAwareAction.async { implicit request =>

    val file = VSimuVersionFileDAO.findById(id)

    serve(file)
  }

def serve(readFileWrapper: ReadFileWrapper, dispositionMode: String = CONTENT_DISPOSITION_ATTACHMENT)(implicit ec: ExecutionContext): Future[Result] = {
    readFileWrapper.readFile.filter(_.isDefined).map(_.get).map { file =>
      val en = readFileWrapper.gfs.enumerate(file)
      val filename = file.filename
      Result(
        // prepare the header
        header = ResponseHeader(OK, Map(
          CONTENT_LENGTH -> ("" + file.length),
          CONTENT_DISPOSITION -> (s"""$dispositionMode; filename="$filename"; filename*=UTF-8''""" + java.net.URLEncoder.encode(filename, "UTF-8").replace("+", "%20")),
          CONTENT_TYPE -> file.contentType.getOrElse("application/octet-stream"))),
        // give Play this file enumerator
        body = en)
    }.recover {
      case _ => NotFound
    }
  }

This comes from MongoController code.

Am I doing something wrong ?

Thanks !

**Comment by fehmicansaglam** [comment]
Can you also paste the stack trace?

**Comment by dsanchez31** [comment]
Here the mongodb error :

2015-04-13T08:38:59.261+0200 E QUERY    [conn14] Plan executor error, stats: { stage: "SORT", nReturned: 0, executionTimeMillisEstimate: 10, works: 131, advance
d: 0, needTime: 129, needFetch: 0, saveState: 1, restoreState: 1, isEOF: 0, invalidates: 0, sortPattern: { n: 1 }, memUsage: 33563392, memLimit: 33554432, input
Stage: { stage: "COLLSCAN", filter: { $and: [ { n: { $lte: 1138 } }, { files_id: { $eq: ObjectId('552b64314cf31db40015dd81') } }, { n: { $gte: 0 } } ] }, nRetur
ned: 128, executionTimeMillisEstimate: 0, works: 129, advanced: 128, needTime: 1, needFetch: 0, saveState: 1, restoreState: 1, isEOF: 0, invalidates: 0, directi
on: "forward", docsExamined: 128 } }
2015-04-13T08:38:59.318+0200 I QUERY    [conn14] assertion 17144 Executor error: Overflow sort stage buffered data usage of 33563392 bytes exceeds internal limi
t of 33554432 bytes ns:vulcan.lm_simu_version.chunks query:{ $query: { files_id: ObjectId('552b64314cf31db40015dd81'), n: { $gte: 0, $lte: 1138 } }, $orderby: {
 n: 1 } }
2015-04-13T08:38:59.324+0200 I QUERY    [conn14] query vulcan.lm_simu_version.chunks query: { $query: { files_id: ObjectId('552b64314cf31db40015dd81'), n: { $gt
e: 0, $lte: 1138 } }, $orderby: { n: 1 } } planSummary: COLLSCAN ntoreturn:0 keyUpdates:0 writeConflicts:0 exception: Executor error: Overflow sort stage buffer
ed data usage of 33563392 bytes exceeds internal limit of 33554432 bytes code:17144 numYields:1 reslen:160 locks:{ Global: { acquireCount: { r: 2 } }, MMAPV1Jou
rnal: { acquireCount: { r: 2 } }, Database: { acquireCount: { r: 2 } }, Collection: { acquireCount: { R: 2 } } } 144ms


How can I get the stack trace ?

**Comment by fehmicansaglam** [comment]
That's quite sufficient. Thanks.

**Comment by cchantep** [comment]
Please note that the MongoController has been updated. If you need more help, you can use the [user MailingList](https://groups.google.com/forum/?fromgroups#!topic/reactivemongo/gC5vLErbq8E) (better to use this issue tracker for confirmed issue). Best regards.
