### ISSUE TITLE
play - Cannot invoke the action, eventually got an error: java.lang.IllegalArgumentException: bound must be positive application - 

### ISSUE THREAD

**Issue by harmeetsingh0013** [ReactiveMongo/ReactiveMongo-Extensions#19]
The issue i face after convert my BSON dao to JSON dao. Some the code is run and some it thrown an exception in JSON Dao. But in BSON dao the code was always run. Following is the detail of problem. 

http://stackoverflow.com/questions/29874795/play-framework-2-3-x-play-cannot-invoke-the-action-eventually-got-an-error

**Comment by cchantep** [comment]
Hi, please ask such question on SO or on the [user MailingList](https://groups.google.com/forum/?fromgroups#!topic/reactivemongo/gC5vLErbq8E), rather than on this issue tracker. Best regards.
