### ISSUE TITLE
How we maintain Object versioning when save the object? 

### ISSUE THREAD

**Issue by harmeetsingh0013** [ReactiveMongo/ReactiveMongo-Extensions#24]
If i want to return `object` or `object id` when save the object in mongo db, we need to maintain versioning on that object with optimistic lock. That also implement by `Spring-Data-Mongodb` and `Mongo-Morphia`. How we maintain versioning in reactive mongo extensions? For full detail of my question, please access below link: 

http://stackoverflow.com/questions/31007400/reactivemongo-return-id-when-save-the-document-in-collection-using-reactivemo

**Comment by cchantep** [comment]
Hi, please do not use this issue tracker to ask question. You can first use the [user MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo), then if an issue is confirmed, a ticket can be filed there. Best regards.
