### ISSUE TITLE
How to use projection in reactivemongo extension? 

### ISSUE THREAD

**Issue by harmeetsingh0013** [ReactiveMongo/ReactiveMongo-Extensions#27]
I have following document: 
```
{
"_id": ObjectId("31231313132"),
"name": "James",
...........
"location":{
 "country": "india"
 }
..........
}
```
From the above document sample, i just want to return `location` filed from query. I am using `reactivemong-extension` JsonDao. In `JsonDao` there are many functions for query, but unable to find how we implement projection with it? 

For more details, please access http://stackoverflow.com/questions/31154428/reactivemongo-projection-element-not-return-using-reactive-mongo-query this link.

**Comment by cchantep** [comment]
Please use the [user Mailing List](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) rather than directly this tracker, which is for confirmed issue. Best regards.
