### ISSUE TITLE
Reactive mongo json extensions on  my Play 2.4.1 application

### ISSUE THREAD

**Issue by dsanchez31** [ReactiveMongo/ReactiveMongo-Extensions#28]
Hi,

I'm migrating my play 2.3.9 application to the last 2.4.1 play version.

Now I'm using "play2-reactivemongo" 0.11.0.play24 version.

But I did not found compatible "reactivemongo-extensions-json" plugin. Do you plan to migrate it ?

Thanks

**Comment by cchantep** [comment]
Hi,

We were focused on migrating the driver and the Play plugin for the release 0.11.
The extensions module is not compatible for now.

If you want to discuss how to migrate your code to 0.11, please use the [user Mailing List](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo).

Best regards
