### ISSUE TITLE
Automatic Generation of from BSONWriter and equivilant to ValueBuilder

### ISSUE THREAD

**Issue by SattaiLanfear** [ReactiveMongo/ReactiveMongo-Extensions#32]
When using the criteria query builders I was surprised to find that types that had valid implicit writers available weren't being automatically adapted.  With a few moments I put this together and it seems to do the job for me, but did leave me wondering if I was misunderstanding the purpose of these ValueBuilders, as they seem entirely redundant with implicit BSONWriters.

```scala
implicit def valueBuilder[X](implicit writer: BSONWriter[X, _ <: BSONValue]): ValueBuilder[X] =
	new ValueBuilder[X] {
		override def bson(v: X): BSONValue = writer.write(v)
	}
```

**Comment by cchantep** [comment]
Hi, please first discuss of such design change on the [MailingList](https://groups.google.com/forum/?fromgroups#!forum/reactivemongo) (this tracker is reserved for confirmed issue). Best regards.
