### ISSUE TITLE
$in doesn't work as expected

### ISSUE THREAD

**Issue by gguan** [ReactiveMongo/ReactiveMongo-Extensions#34]
Hi,
I try to do a query with $in like this: 
"_id" $in Seq(1, 2, 3, 4)

But it was converted to SimpleExpression(_id,{"$in":[[1,2,3,4]]})
It translated to a nested array. 

Any way to resolve this?

**Comment by dsanchez31** [comment]
Just try
"_id" $in (Seq(1,2,3,4) : _*)

**Comment by cchantep** [comment]
Hi, please use the MailingList or SO to ask question. Best regards
