### ISSUE TITLE
How to index GridFS collections

### ISSUE THREAD

**Issue by yanivby** [ReactiveMongo/ReactiveMongo-Extensions#36]
What is the best practice for ensuring that a GridFS collection is indexed correctly?
First there are the indices that the driver is supposed to index, per https://docs.mongodb.org/manual/core/gridfs/#gridfs-indexes
But I also have sometimes additional indices in the files collections (on the files' metadata).
Is there a good place to plug in calls to IndexManager so that I can be sure the indices will be created and ready before the DAO classes are accessed?

**Comment by cchantep** [comment]
Hi, please use the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo) to ask questions. Best regards.

**Comment by yanivby** [comment]
Will do, sorry for this.
