### ISSUE TITLE
Update to 0.12-SNAPSHOT?

### ISSUE THREAD

**Issue by tdrozdowski** [ReactiveMongo/ReactiveMongo-Extensions#39]
I *think* that generally this library works with 0.12-SNAPSHOT (but will know here shortly) - but was wondering if there has been any testing with that version.  About to start a new project, so trying to get everything up to the latest/greatest version before starting.

**Comment by cchantep** [comment]
Hi, first ask question on the [MailingList](https://groups.google.com/forum/m/?fromgroups#!forum/reactivemongo). Best regards.
