### ISSUE TITLE
Documentation for GridFS helpers

### ISSUE THREAD

**Issue by fehmicansaglam** [ReactiveMongo/ReactiveMongo-Extensions#8]

**Comment by dsanchez31** [comment]
Hi,

Can you provide a sample code to show me how to use JsonFileDao  (like the getAttachement method in https://github.com/sgodbillon/reactivemongo-demo-app/blob/master/app/controllers/Application.scala ) ?

Thanks !

**Comment by fehmicansaglam** [comment]
@dsanchez31 there is no complete documentation for GridFS helpers yet. But the test specifications should be helpful: https://github.com/ReactiveMongo/ReactiveMongo-Extensions/blob/0.10.x/json%2Fsrc%2Ftest%2Fscala%2Fdao%2FJsonFileDaoSpec.scala

If not please let me know.

**Comment by dsanchez31** [comment]
sorry I always forget to watch the spec folder :) !
Thanks !
