### ISSUE TITLE
Idea: Evolution case class<->Mongo

### ISSUE THREAD

**Issue by chrissom** [ReactiveMongo/ReactiveMongo-Extensions#9]
Hi,

If i update a case class, i got some json mapping errors because mongodb schema is not up to date.
 
So why not provided a way to push format evolution in collection before starting a scala app? like [Play do it](https://playframework.com/documentation/2.3.x/Evolutions) for sql db.

What do you think?

**Comment by cchantep** [comment]
Such new features can be discussed first on the [user MailingList](https://groups.google.com/forum/?fromgroups#!topic/reactivemongo/gC5vLErbq8E). Best regards.
